CREATE TABLE `restaurant_menu` (
  `id` VARCHAR(36) PRIMARY KEY,
  `menu_name` VARCHAR(128),
  `shop_id` VARCHAR(36) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
