CREATE EXTENSION IF NOT EXISTS postgis;

-- function that creates GEOMETRY point from given inputs
create or replace function create_geometry_point(longitude DOUBLE PRECISION, latitude DOUBLE PRECISION)
  returns GEOMETRY
  language sql 
  immutable 
as $$
  select ST_GeomFromText(CONCAT('POINT(', longitude::text, ' ', latitude::text, ')'))
$$;


CREATE TABLE IF NOT EXISTS shop_address(
  id VARCHAR(36) PRIMARY KEY,
  address1 VARCHAR(256) NOT NULL,
  address2 VARCHAR(256) NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  -- autogenerated 'location' column
  location GEOMETRY GENERATED ALWAYS AS (create_geometry_point(longitude, latitude)) STORED,
  nearby_landmark VARCHAR(128) NOT NULL,
  city VARCHAR(128) NOT NULL,
  state VARCHAR(128) NOT NULL,
  pincode VARCHAR(6) NOT NULL,
  country VARCHAR(128) NOT NULL,
  shop_id VARCHAR(36) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_shop FOREIGN KEY (shop_id) REFERENCES shop(id) ON DELETE CASCADE
);


