CREATE TABLE IF NOT EXISTS shop_contact (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(256) NOT NULL,
  phone_number VARCHAR(10) NOT NULL,
  email VARCHAR(256) NOT NULL,
  shop_id VARCHAR(36) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_shop FOREIGN KEY (shop_id) REFERENCES shop(id) ON DELETE CASCADE
);

