CREATE EXTENSION postgis;

CREATE TABLE IF NOT EXISTS address(
  id VARCHAR(36) PRIMARY KEY,
  address1 VARCHAR(256) NOT NULL,
  address2 VARCHAR(256) NOT NULL,
  location GEOMETRY(Point, 4326),
  landmark VARCHAR(128) NOT NULL,
  city VARCHAR(128) NOT NULL,
  state VARCHAR(128) NOT NULL,
  pincode VARCHAR(6) NOT NULL,
  country VARCHAR(128) NOT NULL,
  shop_id VARCHAR(36) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  CONSTRAINT fk_shop FOREIGN KEY (shop_id) REFERENCES shop(id) ON DELETE CASCADE
);
