CREATE TABLE IF NOT EXISTS `profile`(
  `id` VARCHAR(36) PRIMARY KEY,
  `name` VARCHAR(256) NOT NULL,
  `image_url` VARCHAR(1024) DEFAULT NULL,
  `dob` DATE DEFAULT NULL,
  `anniversary` DATE DEFAULT NULL,
  `gender` ENUM("male", "female", "others", "undisclosed") DEFAULT NULL,
  `auth_id` VARCHAR(36) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);
