- name: Initialize Kubernetes master
  hosts: master
  become: yes
  tasks:
    - name: Initialize Kubernetes
      command: kubeadm init --pod-network-cidr=192.168.0.0/16
      register: kubeadm_init
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Create .kube directory for the ubuntu user
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    - name: Copy Kubernetes admin config to user’s kubeconfig
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        group: ubuntu
        mode: "0644"

    - name: Get the Kubernetes join command
      shell: kubeadm token create --print-join-command
      register: join_command
      changed_when: false

    - name: Save join command to a file
      copy:
        content: "{{ join_command.stdout }}"
        dest: /home/ubuntu/k8s_join.sh
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    - name: Ensure join command is readable
      command: cat /home/ubuntu/k8s_join.sh
      register: verify_join
      changed_when: false

    - name: Fetch join script from master node
      fetch:
        src: /home/ubuntu/k8s_join.sh
        dest: /tmp/k8s_join.sh
        flat: yes
