---
- name: Prepare Nodes
  import_playbook: 01_prep_nodes.yml

- name: Initialize Master Node
  import_playbook: 02_init_master.yml

- name: Join Worker Nodes
  import_playbook: 03_join_workers.yml

- name: Install Calico Networking
  import_playbook: 04_install_calico.yml
