// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: geolocation.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GeolocationService_ReverseGeocode_FullMethodName = "/geolocation.GeolocationService/ReverseGeocode"
)

// GeolocationServiceClient is the client API for GeolocationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GeolocationServiceClient interface {
	ReverseGeocode(ctx context.Context, in *ReverseGeocodeReq, opts ...grpc.CallOption) (*AddressDetail, error)
}

type geolocationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeolocationServiceClient(cc grpc.ClientConnInterface) GeolocationServiceClient {
	return &geolocationServiceClient{cc}
}

func (c *geolocationServiceClient) ReverseGeocode(ctx context.Context, in *ReverseGeocodeReq, opts ...grpc.CallOption) (*AddressDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddressDetail)
	err := c.cc.Invoke(ctx, GeolocationService_ReverseGeocode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeolocationServiceServer is the server API for GeolocationService service.
// All implementations must embed UnimplementedGeolocationServiceServer
// for forward compatibility.
type GeolocationServiceServer interface {
	ReverseGeocode(context.Context, *ReverseGeocodeReq) (*AddressDetail, error)
	mustEmbedUnimplementedGeolocationServiceServer()
}

// UnimplementedGeolocationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeolocationServiceServer struct{}

func (UnimplementedGeolocationServiceServer) ReverseGeocode(context.Context, *ReverseGeocodeReq) (*AddressDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReverseGeocode not implemented")
}
func (UnimplementedGeolocationServiceServer) mustEmbedUnimplementedGeolocationServiceServer() {}
func (UnimplementedGeolocationServiceServer) testEmbeddedByValue()                            {}

// UnsafeGeolocationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeolocationServiceServer will
// result in compilation errors.
type UnsafeGeolocationServiceServer interface {
	mustEmbedUnimplementedGeolocationServiceServer()
}

func RegisterGeolocationServiceServer(s grpc.ServiceRegistrar, srv GeolocationServiceServer) {
	// If the following call pancis, it indicates UnimplementedGeolocationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GeolocationService_ServiceDesc, srv)
}

func _GeolocationService_ReverseGeocode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReverseGeocodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeolocationServiceServer).ReverseGeocode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeolocationService_ReverseGeocode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeolocationServiceServer).ReverseGeocode(ctx, req.(*ReverseGeocodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GeolocationService_ServiceDesc is the grpc.ServiceDesc for GeolocationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeolocationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geolocation.GeolocationService",
	HandlerType: (*GeolocationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReverseGeocode",
			Handler:    _GeolocationService_ReverseGeocode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "geolocation.proto",
}
