// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: product.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductService_CreateItemVariant_FullMethodName      = "/pb.ProductService/CreateItemVariant"
	ProductService_CreateItemAddon_FullMethodName        = "/pb.ProductService/CreateItemAddon"
	ProductService_CreateRestaurantMenu_FullMethodName   = "/pb.ProductService/CreateRestaurantMenu"
	ProductService_CreateMenuItem_FullMethodName         = "/pb.ProductService/CreateMenuItem"
	ProductService_CreateRetailCategory_FullMethodName   = "/pb.ProductService/CreateRetailCategory"
	ProductService_CreateRetailItem_FullMethodName       = "/pb.ProductService/CreateRetailItem"
	ProductService_CreateMedicineCategory_FullMethodName = "/pb.ProductService/CreateMedicineCategory"
	ProductService_CreateMedicineItem_FullMethodName     = "/pb.ProductService/CreateMedicineItem"
	ProductService_GetItemVariant_FullMethodName         = "/pb.ProductService/GetItemVariant"
	ProductService_GetItemVariants_FullMethodName        = "/pb.ProductService/GetItemVariants"
	ProductService_GetItemAddon_FullMethodName           = "/pb.ProductService/GetItemAddon"
	ProductService_GetItemAddons_FullMethodName          = "/pb.ProductService/GetItemAddons"
	ProductService_GetRestaurantMenu_FullMethodName      = "/pb.ProductService/GetRestaurantMenu"
	ProductService_ListRestaurantMenu_FullMethodName     = "/pb.ProductService/ListRestaurantMenu"
	ProductService_GetRetailCategory_FullMethodName      = "/pb.ProductService/GetRetailCategory"
	ProductService_ListRetailCategory_FullMethodName     = "/pb.ProductService/ListRetailCategory"
	ProductService_GetMedicineCategory_FullMethodName    = "/pb.ProductService/GetMedicineCategory"
	ProductService_ListMedicineCategory_FullMethodName   = "/pb.ProductService/ListMedicineCategory"
	ProductService_DeleteItemVariant_FullMethodName      = "/pb.ProductService/DeleteItemVariant"
	ProductService_DeleteItemAddon_FullMethodName        = "/pb.ProductService/DeleteItemAddon"
	ProductService_DeleteRestaurantMenu_FullMethodName   = "/pb.ProductService/DeleteRestaurantMenu"
	ProductService_DeleteMenuItem_FullMethodName         = "/pb.ProductService/DeleteMenuItem"
	ProductService_DeleteRetailCategory_FullMethodName   = "/pb.ProductService/DeleteRetailCategory"
	ProductService_DeleteRetailItem_FullMethodName       = "/pb.ProductService/DeleteRetailItem"
	ProductService_DeleteMedicineCategory_FullMethodName = "/pb.ProductService/DeleteMedicineCategory"
	ProductService_DeleteMedicineItem_FullMethodName     = "/pb.ProductService/DeleteMedicineItem"
)

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductServiceClient interface {
	CreateItemVariant(ctx context.Context, in *CreateItemVariantReq, opts ...grpc.CallOption) (*ItemVariant, error)
	CreateItemAddon(ctx context.Context, in *CreateItemAddonReq, opts ...grpc.CallOption) (*ItemAddon, error)
	CreateRestaurantMenu(ctx context.Context, in *CreateRestaurantMenuReq, opts ...grpc.CallOption) (*RestaurantMenu, error)
	CreateMenuItem(ctx context.Context, in *CreateMenuItemReq, opts ...grpc.CallOption) (*MenuItem, error)
	CreateRetailCategory(ctx context.Context, in *CreateRetailCategoryReq, opts ...grpc.CallOption) (*RetailCategory, error)
	CreateRetailItem(ctx context.Context, in *CreateRetailItemReq, opts ...grpc.CallOption) (*RetailItem, error)
	CreateMedicineCategory(ctx context.Context, in *CreateMedicineCategoryReq, opts ...grpc.CallOption) (*MedicineCategory, error)
	CreateMedicineItem(ctx context.Context, in *CreateMedicineItemReq, opts ...grpc.CallOption) (*MedicineItem, error)
	GetItemVariant(ctx context.Context, in *GetItemVariantReq, opts ...grpc.CallOption) (*ItemVariant, error)
	GetItemVariants(ctx context.Context, in *GetItemVariantsReq, opts ...grpc.CallOption) (*GetItemVariantsRes, error)
	GetItemAddon(ctx context.Context, in *GetItemAddonReq, opts ...grpc.CallOption) (*ItemAddon, error)
	GetItemAddons(ctx context.Context, in *GetItemAddonsReq, opts ...grpc.CallOption) (*GetItemAddonsRes, error)
	GetRestaurantMenu(ctx context.Context, in *GetRestaurantMenuReq, opts ...grpc.CallOption) (*RestaurantMenu, error)
	ListRestaurantMenu(ctx context.Context, in *ListRestaurantMenuReq, opts ...grpc.CallOption) (*ListRestaurantMenuRes, error)
	GetRetailCategory(ctx context.Context, in *GetRetailCategoryReq, opts ...grpc.CallOption) (*RetailCategory, error)
	ListRetailCategory(ctx context.Context, in *ListRetailCategoryReq, opts ...grpc.CallOption) (*ListRetailCategoryRes, error)
	GetMedicineCategory(ctx context.Context, in *GetMedicineCategoryReq, opts ...grpc.CallOption) (*MedicineCategory, error)
	ListMedicineCategory(ctx context.Context, in *ListMedicineCategoryReq, opts ...grpc.CallOption) (*ListMedicineCategoryRes, error)
	DeleteItemVariant(ctx context.Context, in *DeleteItemVariantReq, opts ...grpc.CallOption) (*EmptyRes, error)
	DeleteItemAddon(ctx context.Context, in *DeleteItemAddonReq, opts ...grpc.CallOption) (*EmptyRes, error)
	DeleteRestaurantMenu(ctx context.Context, in *DeleteRestaurantMenuReq, opts ...grpc.CallOption) (*EmptyRes, error)
	DeleteMenuItem(ctx context.Context, in *DeleteMenuItemReq, opts ...grpc.CallOption) (*EmptyRes, error)
	DeleteRetailCategory(ctx context.Context, in *DeleteRetailCategoryReq, opts ...grpc.CallOption) (*EmptyRes, error)
	DeleteRetailItem(ctx context.Context, in *DeleteRetailItemReq, opts ...grpc.CallOption) (*EmptyRes, error)
	DeleteMedicineCategory(ctx context.Context, in *DeleteMedicineCategoryReq, opts ...grpc.CallOption) (*EmptyRes, error)
	DeleteMedicineItem(ctx context.Context, in *DeleteMedicineItemReq, opts ...grpc.CallOption) (*EmptyRes, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) CreateItemVariant(ctx context.Context, in *CreateItemVariantReq, opts ...grpc.CallOption) (*ItemVariant, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemVariant)
	err := c.cc.Invoke(ctx, ProductService_CreateItemVariant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CreateItemAddon(ctx context.Context, in *CreateItemAddonReq, opts ...grpc.CallOption) (*ItemAddon, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemAddon)
	err := c.cc.Invoke(ctx, ProductService_CreateItemAddon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CreateRestaurantMenu(ctx context.Context, in *CreateRestaurantMenuReq, opts ...grpc.CallOption) (*RestaurantMenu, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestaurantMenu)
	err := c.cc.Invoke(ctx, ProductService_CreateRestaurantMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CreateMenuItem(ctx context.Context, in *CreateMenuItemReq, opts ...grpc.CallOption) (*MenuItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuItem)
	err := c.cc.Invoke(ctx, ProductService_CreateMenuItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CreateRetailCategory(ctx context.Context, in *CreateRetailCategoryReq, opts ...grpc.CallOption) (*RetailCategory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetailCategory)
	err := c.cc.Invoke(ctx, ProductService_CreateRetailCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CreateRetailItem(ctx context.Context, in *CreateRetailItemReq, opts ...grpc.CallOption) (*RetailItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetailItem)
	err := c.cc.Invoke(ctx, ProductService_CreateRetailItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CreateMedicineCategory(ctx context.Context, in *CreateMedicineCategoryReq, opts ...grpc.CallOption) (*MedicineCategory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MedicineCategory)
	err := c.cc.Invoke(ctx, ProductService_CreateMedicineCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CreateMedicineItem(ctx context.Context, in *CreateMedicineItemReq, opts ...grpc.CallOption) (*MedicineItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MedicineItem)
	err := c.cc.Invoke(ctx, ProductService_CreateMedicineItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetItemVariant(ctx context.Context, in *GetItemVariantReq, opts ...grpc.CallOption) (*ItemVariant, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemVariant)
	err := c.cc.Invoke(ctx, ProductService_GetItemVariant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetItemVariants(ctx context.Context, in *GetItemVariantsReq, opts ...grpc.CallOption) (*GetItemVariantsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemVariantsRes)
	err := c.cc.Invoke(ctx, ProductService_GetItemVariants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetItemAddon(ctx context.Context, in *GetItemAddonReq, opts ...grpc.CallOption) (*ItemAddon, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemAddon)
	err := c.cc.Invoke(ctx, ProductService_GetItemAddon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetItemAddons(ctx context.Context, in *GetItemAddonsReq, opts ...grpc.CallOption) (*GetItemAddonsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemAddonsRes)
	err := c.cc.Invoke(ctx, ProductService_GetItemAddons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetRestaurantMenu(ctx context.Context, in *GetRestaurantMenuReq, opts ...grpc.CallOption) (*RestaurantMenu, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestaurantMenu)
	err := c.cc.Invoke(ctx, ProductService_GetRestaurantMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ListRestaurantMenu(ctx context.Context, in *ListRestaurantMenuReq, opts ...grpc.CallOption) (*ListRestaurantMenuRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRestaurantMenuRes)
	err := c.cc.Invoke(ctx, ProductService_ListRestaurantMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetRetailCategory(ctx context.Context, in *GetRetailCategoryReq, opts ...grpc.CallOption) (*RetailCategory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetailCategory)
	err := c.cc.Invoke(ctx, ProductService_GetRetailCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ListRetailCategory(ctx context.Context, in *ListRetailCategoryReq, opts ...grpc.CallOption) (*ListRetailCategoryRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRetailCategoryRes)
	err := c.cc.Invoke(ctx, ProductService_ListRetailCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetMedicineCategory(ctx context.Context, in *GetMedicineCategoryReq, opts ...grpc.CallOption) (*MedicineCategory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MedicineCategory)
	err := c.cc.Invoke(ctx, ProductService_GetMedicineCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ListMedicineCategory(ctx context.Context, in *ListMedicineCategoryReq, opts ...grpc.CallOption) (*ListMedicineCategoryRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMedicineCategoryRes)
	err := c.cc.Invoke(ctx, ProductService_ListMedicineCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteItemVariant(ctx context.Context, in *DeleteItemVariantReq, opts ...grpc.CallOption) (*EmptyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyRes)
	err := c.cc.Invoke(ctx, ProductService_DeleteItemVariant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteItemAddon(ctx context.Context, in *DeleteItemAddonReq, opts ...grpc.CallOption) (*EmptyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyRes)
	err := c.cc.Invoke(ctx, ProductService_DeleteItemAddon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteRestaurantMenu(ctx context.Context, in *DeleteRestaurantMenuReq, opts ...grpc.CallOption) (*EmptyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyRes)
	err := c.cc.Invoke(ctx, ProductService_DeleteRestaurantMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteMenuItem(ctx context.Context, in *DeleteMenuItemReq, opts ...grpc.CallOption) (*EmptyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyRes)
	err := c.cc.Invoke(ctx, ProductService_DeleteMenuItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteRetailCategory(ctx context.Context, in *DeleteRetailCategoryReq, opts ...grpc.CallOption) (*EmptyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyRes)
	err := c.cc.Invoke(ctx, ProductService_DeleteRetailCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteRetailItem(ctx context.Context, in *DeleteRetailItemReq, opts ...grpc.CallOption) (*EmptyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyRes)
	err := c.cc.Invoke(ctx, ProductService_DeleteRetailItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteMedicineCategory(ctx context.Context, in *DeleteMedicineCategoryReq, opts ...grpc.CallOption) (*EmptyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyRes)
	err := c.cc.Invoke(ctx, ProductService_DeleteMedicineCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteMedicineItem(ctx context.Context, in *DeleteMedicineItemReq, opts ...grpc.CallOption) (*EmptyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyRes)
	err := c.cc.Invoke(ctx, ProductService_DeleteMedicineItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
// All implementations must embed UnimplementedProductServiceServer
// for forward compatibility.
type ProductServiceServer interface {
	CreateItemVariant(context.Context, *CreateItemVariantReq) (*ItemVariant, error)
	CreateItemAddon(context.Context, *CreateItemAddonReq) (*ItemAddon, error)
	CreateRestaurantMenu(context.Context, *CreateRestaurantMenuReq) (*RestaurantMenu, error)
	CreateMenuItem(context.Context, *CreateMenuItemReq) (*MenuItem, error)
	CreateRetailCategory(context.Context, *CreateRetailCategoryReq) (*RetailCategory, error)
	CreateRetailItem(context.Context, *CreateRetailItemReq) (*RetailItem, error)
	CreateMedicineCategory(context.Context, *CreateMedicineCategoryReq) (*MedicineCategory, error)
	CreateMedicineItem(context.Context, *CreateMedicineItemReq) (*MedicineItem, error)
	GetItemVariant(context.Context, *GetItemVariantReq) (*ItemVariant, error)
	GetItemVariants(context.Context, *GetItemVariantsReq) (*GetItemVariantsRes, error)
	GetItemAddon(context.Context, *GetItemAddonReq) (*ItemAddon, error)
	GetItemAddons(context.Context, *GetItemAddonsReq) (*GetItemAddonsRes, error)
	GetRestaurantMenu(context.Context, *GetRestaurantMenuReq) (*RestaurantMenu, error)
	ListRestaurantMenu(context.Context, *ListRestaurantMenuReq) (*ListRestaurantMenuRes, error)
	GetRetailCategory(context.Context, *GetRetailCategoryReq) (*RetailCategory, error)
	ListRetailCategory(context.Context, *ListRetailCategoryReq) (*ListRetailCategoryRes, error)
	GetMedicineCategory(context.Context, *GetMedicineCategoryReq) (*MedicineCategory, error)
	ListMedicineCategory(context.Context, *ListMedicineCategoryReq) (*ListMedicineCategoryRes, error)
	DeleteItemVariant(context.Context, *DeleteItemVariantReq) (*EmptyRes, error)
	DeleteItemAddon(context.Context, *DeleteItemAddonReq) (*EmptyRes, error)
	DeleteRestaurantMenu(context.Context, *DeleteRestaurantMenuReq) (*EmptyRes, error)
	DeleteMenuItem(context.Context, *DeleteMenuItemReq) (*EmptyRes, error)
	DeleteRetailCategory(context.Context, *DeleteRetailCategoryReq) (*EmptyRes, error)
	DeleteRetailItem(context.Context, *DeleteRetailItemReq) (*EmptyRes, error)
	DeleteMedicineCategory(context.Context, *DeleteMedicineCategoryReq) (*EmptyRes, error)
	DeleteMedicineItem(context.Context, *DeleteMedicineItemReq) (*EmptyRes, error)
	mustEmbedUnimplementedProductServiceServer()
}

// UnimplementedProductServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductServiceServer struct{}

func (UnimplementedProductServiceServer) CreateItemVariant(context.Context, *CreateItemVariantReq) (*ItemVariant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateItemVariant not implemented")
}
func (UnimplementedProductServiceServer) CreateItemAddon(context.Context, *CreateItemAddonReq) (*ItemAddon, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateItemAddon not implemented")
}
func (UnimplementedProductServiceServer) CreateRestaurantMenu(context.Context, *CreateRestaurantMenuReq) (*RestaurantMenu, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRestaurantMenu not implemented")
}
func (UnimplementedProductServiceServer) CreateMenuItem(context.Context, *CreateMenuItemReq) (*MenuItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMenuItem not implemented")
}
func (UnimplementedProductServiceServer) CreateRetailCategory(context.Context, *CreateRetailCategoryReq) (*RetailCategory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRetailCategory not implemented")
}
func (UnimplementedProductServiceServer) CreateRetailItem(context.Context, *CreateRetailItemReq) (*RetailItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRetailItem not implemented")
}
func (UnimplementedProductServiceServer) CreateMedicineCategory(context.Context, *CreateMedicineCategoryReq) (*MedicineCategory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMedicineCategory not implemented")
}
func (UnimplementedProductServiceServer) CreateMedicineItem(context.Context, *CreateMedicineItemReq) (*MedicineItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMedicineItem not implemented")
}
func (UnimplementedProductServiceServer) GetItemVariant(context.Context, *GetItemVariantReq) (*ItemVariant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemVariant not implemented")
}
func (UnimplementedProductServiceServer) GetItemVariants(context.Context, *GetItemVariantsReq) (*GetItemVariantsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemVariants not implemented")
}
func (UnimplementedProductServiceServer) GetItemAddon(context.Context, *GetItemAddonReq) (*ItemAddon, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemAddon not implemented")
}
func (UnimplementedProductServiceServer) GetItemAddons(context.Context, *GetItemAddonsReq) (*GetItemAddonsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemAddons not implemented")
}
func (UnimplementedProductServiceServer) GetRestaurantMenu(context.Context, *GetRestaurantMenuReq) (*RestaurantMenu, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRestaurantMenu not implemented")
}
func (UnimplementedProductServiceServer) ListRestaurantMenu(context.Context, *ListRestaurantMenuReq) (*ListRestaurantMenuRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRestaurantMenu not implemented")
}
func (UnimplementedProductServiceServer) GetRetailCategory(context.Context, *GetRetailCategoryReq) (*RetailCategory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRetailCategory not implemented")
}
func (UnimplementedProductServiceServer) ListRetailCategory(context.Context, *ListRetailCategoryReq) (*ListRetailCategoryRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRetailCategory not implemented")
}
func (UnimplementedProductServiceServer) GetMedicineCategory(context.Context, *GetMedicineCategoryReq) (*MedicineCategory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMedicineCategory not implemented")
}
func (UnimplementedProductServiceServer) ListMedicineCategory(context.Context, *ListMedicineCategoryReq) (*ListMedicineCategoryRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMedicineCategory not implemented")
}
func (UnimplementedProductServiceServer) DeleteItemVariant(context.Context, *DeleteItemVariantReq) (*EmptyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteItemVariant not implemented")
}
func (UnimplementedProductServiceServer) DeleteItemAddon(context.Context, *DeleteItemAddonReq) (*EmptyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteItemAddon not implemented")
}
func (UnimplementedProductServiceServer) DeleteRestaurantMenu(context.Context, *DeleteRestaurantMenuReq) (*EmptyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRestaurantMenu not implemented")
}
func (UnimplementedProductServiceServer) DeleteMenuItem(context.Context, *DeleteMenuItemReq) (*EmptyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMenuItem not implemented")
}
func (UnimplementedProductServiceServer) DeleteRetailCategory(context.Context, *DeleteRetailCategoryReq) (*EmptyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRetailCategory not implemented")
}
func (UnimplementedProductServiceServer) DeleteRetailItem(context.Context, *DeleteRetailItemReq) (*EmptyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRetailItem not implemented")
}
func (UnimplementedProductServiceServer) DeleteMedicineCategory(context.Context, *DeleteMedicineCategoryReq) (*EmptyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMedicineCategory not implemented")
}
func (UnimplementedProductServiceServer) DeleteMedicineItem(context.Context, *DeleteMedicineItemReq) (*EmptyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMedicineItem not implemented")
}
func (UnimplementedProductServiceServer) mustEmbedUnimplementedProductServiceServer() {}
func (UnimplementedProductServiceServer) testEmbeddedByValue()                        {}

// UnsafeProductServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductServiceServer will
// result in compilation errors.
type UnsafeProductServiceServer interface {
	mustEmbedUnimplementedProductServiceServer()
}

func RegisterProductServiceServer(s grpc.ServiceRegistrar, srv ProductServiceServer) {
	// If the following call pancis, it indicates UnimplementedProductServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductService_ServiceDesc, srv)
}

func _ProductService_CreateItemVariant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItemVariantReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateItemVariant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_CreateItemVariant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateItemVariant(ctx, req.(*CreateItemVariantReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CreateItemAddon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItemAddonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateItemAddon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_CreateItemAddon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateItemAddon(ctx, req.(*CreateItemAddonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CreateRestaurantMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRestaurantMenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateRestaurantMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_CreateRestaurantMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateRestaurantMenu(ctx, req.(*CreateRestaurantMenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CreateMenuItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMenuItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateMenuItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_CreateMenuItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateMenuItem(ctx, req.(*CreateMenuItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CreateRetailCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRetailCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateRetailCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_CreateRetailCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateRetailCategory(ctx, req.(*CreateRetailCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CreateRetailItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRetailItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateRetailItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_CreateRetailItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateRetailItem(ctx, req.(*CreateRetailItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CreateMedicineCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMedicineCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateMedicineCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_CreateMedicineCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateMedicineCategory(ctx, req.(*CreateMedicineCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CreateMedicineItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMedicineItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateMedicineItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_CreateMedicineItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateMedicineItem(ctx, req.(*CreateMedicineItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetItemVariant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemVariantReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetItemVariant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetItemVariant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetItemVariant(ctx, req.(*GetItemVariantReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetItemVariants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemVariantsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetItemVariants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetItemVariants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetItemVariants(ctx, req.(*GetItemVariantsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetItemAddon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemAddonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetItemAddon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetItemAddon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetItemAddon(ctx, req.(*GetItemAddonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetItemAddons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemAddonsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetItemAddons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetItemAddons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetItemAddons(ctx, req.(*GetItemAddonsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetRestaurantMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRestaurantMenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetRestaurantMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetRestaurantMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetRestaurantMenu(ctx, req.(*GetRestaurantMenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ListRestaurantMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRestaurantMenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ListRestaurantMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_ListRestaurantMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ListRestaurantMenu(ctx, req.(*ListRestaurantMenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetRetailCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRetailCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetRetailCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetRetailCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetRetailCategory(ctx, req.(*GetRetailCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ListRetailCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRetailCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ListRetailCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_ListRetailCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ListRetailCategory(ctx, req.(*ListRetailCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetMedicineCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMedicineCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetMedicineCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetMedicineCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetMedicineCategory(ctx, req.(*GetMedicineCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ListMedicineCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMedicineCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ListMedicineCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_ListMedicineCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ListMedicineCategory(ctx, req.(*ListMedicineCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteItemVariant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteItemVariantReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteItemVariant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_DeleteItemVariant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteItemVariant(ctx, req.(*DeleteItemVariantReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteItemAddon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteItemAddonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteItemAddon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_DeleteItemAddon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteItemAddon(ctx, req.(*DeleteItemAddonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteRestaurantMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRestaurantMenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteRestaurantMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_DeleteRestaurantMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteRestaurantMenu(ctx, req.(*DeleteRestaurantMenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteMenuItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMenuItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteMenuItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_DeleteMenuItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteMenuItem(ctx, req.(*DeleteMenuItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteRetailCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRetailCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteRetailCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_DeleteRetailCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteRetailCategory(ctx, req.(*DeleteRetailCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteRetailItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRetailItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteRetailItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_DeleteRetailItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteRetailItem(ctx, req.(*DeleteRetailItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteMedicineCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMedicineCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteMedicineCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_DeleteMedicineCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteMedicineCategory(ctx, req.(*DeleteMedicineCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteMedicineItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMedicineItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteMedicineItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_DeleteMedicineItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteMedicineItem(ctx, req.(*DeleteMedicineItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductService_ServiceDesc is the grpc.ServiceDesc for ProductService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateItemVariant",
			Handler:    _ProductService_CreateItemVariant_Handler,
		},
		{
			MethodName: "CreateItemAddon",
			Handler:    _ProductService_CreateItemAddon_Handler,
		},
		{
			MethodName: "CreateRestaurantMenu",
			Handler:    _ProductService_CreateRestaurantMenu_Handler,
		},
		{
			MethodName: "CreateMenuItem",
			Handler:    _ProductService_CreateMenuItem_Handler,
		},
		{
			MethodName: "CreateRetailCategory",
			Handler:    _ProductService_CreateRetailCategory_Handler,
		},
		{
			MethodName: "CreateRetailItem",
			Handler:    _ProductService_CreateRetailItem_Handler,
		},
		{
			MethodName: "CreateMedicineCategory",
			Handler:    _ProductService_CreateMedicineCategory_Handler,
		},
		{
			MethodName: "CreateMedicineItem",
			Handler:    _ProductService_CreateMedicineItem_Handler,
		},
		{
			MethodName: "GetItemVariant",
			Handler:    _ProductService_GetItemVariant_Handler,
		},
		{
			MethodName: "GetItemVariants",
			Handler:    _ProductService_GetItemVariants_Handler,
		},
		{
			MethodName: "GetItemAddon",
			Handler:    _ProductService_GetItemAddon_Handler,
		},
		{
			MethodName: "GetItemAddons",
			Handler:    _ProductService_GetItemAddons_Handler,
		},
		{
			MethodName: "GetRestaurantMenu",
			Handler:    _ProductService_GetRestaurantMenu_Handler,
		},
		{
			MethodName: "ListRestaurantMenu",
			Handler:    _ProductService_ListRestaurantMenu_Handler,
		},
		{
			MethodName: "GetRetailCategory",
			Handler:    _ProductService_GetRetailCategory_Handler,
		},
		{
			MethodName: "ListRetailCategory",
			Handler:    _ProductService_ListRetailCategory_Handler,
		},
		{
			MethodName: "GetMedicineCategory",
			Handler:    _ProductService_GetMedicineCategory_Handler,
		},
		{
			MethodName: "ListMedicineCategory",
			Handler:    _ProductService_ListMedicineCategory_Handler,
		},
		{
			MethodName: "DeleteItemVariant",
			Handler:    _ProductService_DeleteItemVariant_Handler,
		},
		{
			MethodName: "DeleteItemAddon",
			Handler:    _ProductService_DeleteItemAddon_Handler,
		},
		{
			MethodName: "DeleteRestaurantMenu",
			Handler:    _ProductService_DeleteRestaurantMenu_Handler,
		},
		{
			MethodName: "DeleteMenuItem",
			Handler:    _ProductService_DeleteMenuItem_Handler,
		},
		{
			MethodName: "DeleteRetailCategory",
			Handler:    _ProductService_DeleteRetailCategory_Handler,
		},
		{
			MethodName: "DeleteRetailItem",
			Handler:    _ProductService_DeleteRetailItem_Handler,
		},
		{
			MethodName: "DeleteMedicineCategory",
			Handler:    _ProductService_DeleteMedicineCategory_Handler,
		},
		{
			MethodName: "DeleteMedicineItem",
			Handler:    _ProductService_DeleteMedicineItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}
