// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"fmt"
	"io"
	"strconv"
)

type Auth struct {
	ID            string   `json:"id"`
	Email         *string  `json:"email,omitempty"`
	EmailVerified *bool    `json:"email_verified,omitempty"`
	Phone         *string  `json:"phone,omitempty"`
	Type          AuthType `json:"type"`
	CreatedAt     string   `json:"created_at"`
	UpdatedAt     string   `json:"updated_at"`
	DeletedAt     *string  `json:"deleted_at,omitempty"`
}

type GetAuthByIDInput struct {
	ID string `json:"id"`
}

type GetAuthInput struct {
	Email *string `json:"email,omitempty"`
	Phone *string `json:"phone,omitempty"`
}

type Mutation struct {
}

type Profile struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	ImageURL    *string `json:"image_url,omitempty"`
	Dob         *string `json:"dob,omitempty"`
	Anniversary *string `json:"anniversary,omitempty"`
	Gender      *Gender `json:"gender,omitempty"`
	AuthID      string  `json:"auth_id"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
}

type Query struct {
}

type SignInWithEmailInput struct {
	Email string  `json:"email"`
	Otp   *string `json:"otp,omitempty"`
}

type SignInWithGoogleInput struct {
	IDToken string `json:"id_token"`
}

type SignInWithPhoneInput struct {
	Phone string  `json:"phone"`
	Otp   *string `json:"otp,omitempty"`
}

type User struct {
	Auth    *Auth    `json:"auth"`
	Profile *Profile `json:"profile,omitempty"`
}

type AuthType string

const (
	AuthTypeCustomer        AuthType = "CUSTOMER"
	AuthTypeDeliveryPartner AuthType = "DELIVERY_PARTNER"
	AuthTypeVendor          AuthType = "VENDOR"
	AuthTypeAdmin           AuthType = "ADMIN"
)

var AllAuthType = []AuthType{
	AuthTypeCustomer,
	AuthTypeDeliveryPartner,
	AuthTypeVendor,
	AuthTypeAdmin,
}

func (e AuthType) IsValid() bool {
	switch e {
	case AuthTypeCustomer, AuthTypeDeliveryPartner, AuthTypeVendor, AuthTypeAdmin:
		return true
	}
	return false
}

func (e AuthType) String() string {
	return string(e)
}

func (e *AuthType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AuthType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AuthType", str)
	}
	return nil
}

func (e AuthType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Gender string

const (
	GenderMale        Gender = "MALE"
	GenderFemale      Gender = "FEMALE"
	GenderOthers      Gender = "OTHERS"
	GenderUndisclosed Gender = "UNDISCLOSED"
)

var AllGender = []Gender{
	GenderMale,
	GenderFemale,
	GenderOthers,
	GenderUndisclosed,
}

func (e Gender) IsValid() bool {
	switch e {
	case GenderMale, GenderFemale, GenderOthers, GenderUndisclosed:
		return true
	}
	return false
}

func (e Gender) String() string {
	return string(e)
}

func (e *Gender) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Gender(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Gender", str)
	}
	return nil
}

func (e Gender) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
